#!/bin/bash

set -e -o pipefail

if [ -z "$1" ]; then
    dir="$(dirname $0)/../sample_input_files"
else
    dir=$1
fi

find "$dir" -name '*.csv' -a -not -path '*output*' -print0 | while IFS= read -r -d $'\0' csv; do
    h5=${csv/.csv/.h5}
    echo Converting $csv to $h5
    python -m simple_network_sim.csv_to_hdf5 "$csv" "$h5"
done
